FROM python:3.9-slim
RUN apt update && apt install -y build-essential
ADD /src /src
RUN pip install -r /src/requirements.txt
RUN adduser --system --no-create-home secretmonkey
USER secretmonkey
CMD kopf run --liveness=http://[::]:8080/healthz -A /src/handlers.py
