---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clustersecret-io-v2-clustersecret
  failurePolicy: Fail
  name: mclustersecret.kb.io
  rules:
  - apiGroups:
    - clustersecret.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - clustersecrets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clustersecret-io-v2-clustersecret
  failurePolicy: Fail
  name: vclustersecret.kb.io
  rules:
  - apiGroups:
    - clustersecret.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - clustersecrets
  sideEffects: None
