# permissions for end users to edit clustersecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clustersecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: clustersecret-operator
    app.kubernetes.io/part-of: clustersecret-operator
    app.kubernetes.io/managed-by: kustomize
  name: clustersecret-editor-role
rules:
- apiGroups:
  - clustersecret.io
  resources:
  - clustersecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustersecret.io
  resources:
  - clustersecrets/status
  verbs:
  - get
