---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustersecret.io
  resources:
  - clustersecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustersecret.io
  resources:
  - clustersecrets/finalizers
  verbs:
  - update
- apiGroups:
  - clustersecret.io
  resources:
  - clustersecrets/status
  verbs:
  - get
  - patch
  - update
