apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  labels:
    app.kubernetes.io/name: clustersecret-operator
    app.kubernetes.io/managed-by: kustomize
  name: clustersecret-v1-sample
type: Opaque
matchNamespace:
  - foo.*
avoidNamespaces:
  - kube-.*
data:
  a: bG9yZW0=
