apiVersion: v1
kind: Secret
metadata:
  name: clustersecret-datavaluefrom-1
  namespace: default
stringData:
  unused: this key is not used by ClusterSecret
  foo: bar
---
apiVersion: v1
kind: Secret
metadata:
  name: clustersecret-datavaluefrom-2
  namespace: default
stringData:
  unused: this key is not used by ClusterSecret
  moo: doo
---
apiVersion: clustersecret.io/v2
kind: ClusterSecret
metadata:
  labels:
    app.kubernetes.io/name: clustersecret-operator
    app.kubernetes.io/managed-by: kustomize
  name: datavaluefrom
spec:
  # Terms are ORed, meaning it matches a namespace if any of the terms match.
  namespaceSelectorTerms:
    - matchFields:
        # Field matcher requirements are ANDed together,
        # meaning all of them have to match.

        - key: metadata.name
          operator: InRegex
          values:
            # Field values are ORed together,
            # meaning any of the values have to match the key.
            - foo.*

        - key: metadata.name
          operator: NotInRegex
          values:
            - kube-.*

  dataValueFrom:
    foo:
      secretKeyRef:
        name: clustersecret-datavaluefrom-1
        namespace: default
        key: foo
    renamed-moo:
      secretKeyRef:
        name: clustersecret-datavaluefrom-2
        namespace: default
        key: moo

  template:
    data:
      myAdditionalData: bG9yZW0=
