apiVersion: clustersecret.io/v2
kind: ClusterSecret
metadata:
  labels:
    app.kubernetes.io/name: clustersecret-operator
    app.kubernetes.io/managed-by: kustomize
  name: clustersecret-sample
spec:
  # Terms are ORed, meaning it matches a namespace if any of the terms match.
  namespaceSelectorTerms:
    - matchFields:
        # Field matcher requirements are ANDed together,
        # meaning all of them have to match.

        - key: metadata.name
          operator: InRegex
          values:
            # Field values are ORed together,
            # meaning any of the values have to match the key.
            - foo.*

        - key: metadata.name
          operator: NotInRegex
          values:
            - kube-.*

  template:
    data:
      a: bG9yZW0=
    stringData:
      b: ipsum
